### ISSUE TITLE
Base.url_decode64

### ISSUE THREAD

**Issue by InoMurko** [ntrepid8/ex_crypto#1]
Hi,

what's the reason to use url_decode64 and not decode64?
https://github.com/ntrepid8/ex_crypto/blob/master/lib/ex_public_key.ex#L166

**Comment by ntrepid8** [comment]
The main reason was just to be consistent in the library about how we encode/decode.  There are times when it's convenient to pass tokens in the query string of a GET HTTP request and since those require URL safe encoding I just went with that.

Is it causing problems for something you want to use the library for?

**Comment by InoMurko** [comment]
To be consistent it makes sense. But my impression is that bare 64 is more popular or more often used then url 64. But you're right, depends for what you're using it for. 
We're using encode16 and 64 for other things - consistency wise it would not suite us to use url_encode64. 

Maybe something we could make configurable?

**Comment by ntrepid8** [comment]
I think we can do an optional keyword list where options like that can be passed in.  Would that work for your use case?

**Comment by InoMurko** [comment]
Definitely. Much appreciated!
